### ISSUE TITLE
Avoid renaming logging as log

### ISSUE THREAD

**Issue by nerdling** [hillaxj/NCAABracketMaker#8]
It's common to create a `log` variable as the current module's logger. Since a module may import additional modules (such as if another program uses NCAABracketMaker), it's generally considered good form to set your own up instead of using the default logger.

https://docs.python.org/3/library/logging.html#logger-objects

An example could be as simple as:
```
logging.basicConfig(level=logging.INFO, format="[%(levelname)-8s] %(message)s")
log = logging.getLogger(__name__)
```

**Comment by hillaxj** [comment]
Resolved in develop branch
